### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by Fadfadet** [Skullfox/maiq-the-liar-public#5]
Is it possible to have the full bot in another language than English?
As only some parts are in French when I select the french version, for example : pledges names are in french but not the NPC's names.. etc. Would be great to have an all-french one!
I can help translating if needed! :D

**Comment by Skullfox** [comment]
French is partial available, use `!pledges fr`.
More translation is tbd.

**Comment by Skullfox** [comment]
checkout #12 ive created a google sheet for the translations.
